### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by NobodyForYouCreator** [CodeWithSwastik/prsaw#12]
Hi, using this package and I can't get response on Russian or Hebrew (idk if there're other languages)

```py
from prsaw import RandomStuff    


rs = RandomStuff(async_mode=True)


@commands.Cog.listener()
    async def on_message(self, message):
        if self.client.user == message.author:
            return
        post = {'_id':message.guild.id} 
        data = coll.find_one(post) # coll - MongoDataBase
        if data != None: #Checking if guild has specific channel
            if message.channel.id == data['id']: #If exists it tries to find channel with chatbot
                if message.content == f'{pref(self.client, message)}chatbotdel' or message.content == f'{pref(self.client, message)}chatbotset' or message.content == f'{pref(self.client, message)}chatbot': #Commands, that i can run in channel with chatbot
                    return await self.client.process_commands(message)
                response = await rs.get_ai_response(message.content) #Getting response
                await message.reply(response) #Sending response

                return
        else:
            await self.client.process_commands(message) #If not chatbot, its usual command
```

**Comment by ghost** [comment]
So this might be because @pgamerxdev's API doesn't support those specific languages. prsaw is just a **api wrapper for random-stuff-api**

I'd say you open an issue in @pgamerxdev's API's repo about adding more languages. 
Technically there's nothing prsaw could do about this unless the core API was changed.

**Comment by ghost** [comment]
Also sorry PGamerX for the pings :/

**Comment by pgamerx** [comment]
> So this might be because @pgamerxdev's API doesn't support those specific languages. prsaw is just a **api wrapper for random-stuff-api**
> 
> I'd say you open an issue in @pgamerxdev's API's repo about adding more languages.
> Technically there's nothing prsaw could do about this unless the core API was changed.

There is no option in prsaw to select language, go ahead and blame @FalseDev for that
Also yes, in my api currently multi-language stuff is disabled for some time
Because you know the reason

**Comment by FalseDev** [comment]
> There is no option in prsaw to select language, go ahead and blame @FalseDev for that
> Also yes, in my api currently multi-language stuff is disabled for some time
> Because you know the reason

Please provide your API's openapi-v3 schema and I'll ensure full coverage 😄

**Comment by pgamerx** [comment]
> > There is no option in prsaw to select language, go ahead and blame @FalseDev for that
> > Also yes, in my api currently multi-language stuff is disabled for some time
> > Because you know the reason
> 
> Please provide your API's openapi-v3 schema and I'll ensure full coverage 😄

https://app.swaggerhub.com/apis/pgamerxdev/random-stuff-api/2.0

**Comment by izxxr** [comment]
Shouldn't this be closed by now?
