### ISSUE TITLE
Unrelated answers 

### ISSUE THREAD

**Issue by RitoprovoRoy** [CodeWithSwastik/prsaw#13]
I programmed my AI bot using the PRSAW package and it used to work fine. But recently it's giving a lot of unrelated answers to questions. 
For example :
Question: "How are you ?"
Answer from the bot: "What do you like to eat?"

Were there any recent updates to this wrapper? Or am I doing something wrong?

**Comment by sachin-sankar** [comment]
Did you close the session using `await rs.close()` ?

**Comment by CoblinFrog** [comment]
May I see your code?

**Comment by RitoprovoRoy** [comment]
1. No I didn't use await rs.close(). 
2. Yes. Can I show that to you on discord? Sharing there for me will be much more convenient.

**Comment by sachin-sankar** [comment]
@RitoprovoRoy If you want I can.

**Comment by RitoprovoRoy** [comment]
@Creepy-Creeper3625 please share your discord link and I am posting it there

**Comment by ghost** [comment]
@RitoprovoRoy the API is just like that. The people who made prsaw are just making a wrapper for the api, they can't change the responses.

Please update your prsaw anyways (`sudo python3 -m pip3 install -U prsaw` on ubuntu). 
Sometimes the API loses context but that's the hard part in building an AI response.

**Comment by Makiyu-py** [comment]
> I programmed my AI bot using the PRSAW package and it used to work fine. But recently it's giving a lot of unrelated answers to questions.
> For example :
> Question: "How are you ?"
> Answer from the bot: "What do you like to eat?"
> 
> Were there any recent updates to this wrapper? Or am I doing something wrong?

I suppose this is a problem to the API itself, not the wrapper. Issue your problem [in this repo](https://github.com/pgamerxdev/projects) for API problems.

**Comment by pgamerx** [comment]
> > I programmed my AI bot using the PRSAW package and it used to work fine. But recently it's giving a lot of unrelated answers to questions.
> > For example :
> > Question: "How are you ?"
> > Answer from the bot: "What do you like to eat?"
> > Were there any recent updates to this wrapper? Or am I doing something wrong?
> 
> I suppose this is a problem to the API itself, not the wrapper. Issue your problem [in this repo](https://github.com/pgamerxdev/projects) for API problems.

It isn't as of now
I fixed a lot and lot of bugs in Version 3 
But The maintainers aren't updating the package.
I am currently working on my own wrapper for my api if there is no solution to this problem

**Comment by ghost** [comment]
@pgamerxdev can't swastik or false update prsaw to version 3? 
~~no offence but the other day you didn't even know how to create a pip package~~

**Comment by pgamerx** [comment]
> @pgamerxdev can't swastik or false update prsaw to version 3?
> ~no offence but the other day you didn't even know how to create a pip package~

They are not doing it, what can I do?

**Comment by CodeWithSwastik** [comment]
Support for Version 3 has been added.

**Comment by pgamerx** [comment]
> Support for Version 3 has been added.

Epic

**Comment by abilash2409** [comment]
![Screenshot_20220127-214948_Discord.jpg](https://user-images.githubusercontent.com/89125818/151399544-a6d54475-3d4b-469b-b26e-3c533be9cca0.jpg)

BOT is replying me like this please help me

**Comment by pgamerx** [comment]
Please check the website of Random Stuff Api, we are now only usable throug RapidAPI, all code examples are available on the Rapidapi page as well. 

https://api.pgamerx.com
