### ISSUE TITLE
Session Can't Close on Async Mode

### ISSUE THREAD

**Issue by Makiyu-py** [CodeWithSwastik/prsaw#17]
Hi! There's a big problem with prsaw that I already told False about.

## You can't close the session when it is on async mode
[Someone on help channels](https://discord.com/channels/681882711945641997/767641504092913674/837212378289930250) in TCA had this problem. I thought u had to just `await` it, but it's not like that since the function is not asynchronous. It gave this error:
```
'AsyncClient' object has no attribute 'close'
```
### I did some research about this and...
I saw that the **`close` function only applies to `httpx.Client`** which is the default client used

But async mode **uses `httpx.AsyncClient`** which uses a **coroutine** named `aclose` to close the session

#### Please find a way to fix this problem, ty!

**Comment by Makiyu-py** [comment]
I've did some digging here on this repo and apparently someone also have this problem too (#3). Swas gave the normal `await` answer, this is wrong since me [and False](https://discord.com/channels/681882711945641997/819102764771573770/837216696896979004) already tried that before.

**Comment by Makiyu-py** [comment]
> I've did some digging here on this repo and apparently someone also have this problem too (#3). Swas gave the normal `await` answer, this is wrong since me [and False](https://discord.com/channels/681882711945641997/819102764771573770/837216696896979004) already tried that before.

.... which means that the example given in the readme is also wrong.

**Comment by izxxr** [comment]
Tried to fix this in existing `close` function but it didn't work so I created a completely new method, `RandomStuff.aclose()` that closes the `httpx.AsyncClient`.

#19 PR fixes this problem.

**Comment by pgamerx** [comment]
> Tried to fix this in existing `close` function but it didn't work so I created a completely new method, `RandomStuff.aclose()` that closes the `httpx.AsyncClient`.
> 
> #19 PR fixes this problem.

Chance of them accepting that pr is below zero

**Comment by izxxr** [comment]
> > Tried to fix this in existing `close` function but it didn't work so I created a completely new method, `RandomStuff.aclose()` that closes the `httpx.AsyncClient`.
> > #19 PR fixes this problem.
> 
> Chance of them accepting that pr is below zero

This wrapper is way outdated now since API is near to v4. It was many days ago when I opened that PR and true that they're not gonna add it.

**Comment by pgamerx** [comment]
> > > Tried to fix this in existing `close` function but it didn't work so I created a completely new method, `RandomStuff.aclose()` that closes the `httpx.AsyncClient`.
> > > #19 PR fixes this problem.
> > 
> > Chance of them accepting that pr is below zero
> 
> This wrapper is way outdated now since API is near to v4. It was many days ago when I opened that PR and true that they're not gonna add it. 

I know right, I don't know why they won't update the package. 
Anyway, it's their audience getting hurt.
Also , I wonder what will happen next week

**Comment by izxxr** [comment]
Same :eyes:

**Comment by CodeWithSwastik** [comment]
> Tried to fix this in existing `close` function but it didn't work so I created a completely new method, `RandomStuff.aclose()` that closes the `httpx.AsyncClient`.
> 
> #19 PR fixes this problem.

I'll close this since, we've accepted #19
