### ISSUE TITLE
'AsyncClient' object has no attribute 'close'

### ISSUE THREAD

**Issue by MarzaElise** [CodeWithSwastik/prsaw#3]
I used prsaw in my discord.py bot to have a chatbot kind of thing. U used it with the exact syntax in [https://pypi.org/project/prsaw/](https://pypi.org/project/prsaw/)
I used it with `async_mode=True` obviously because im doing it for a discord bot. That is when i discovered this error. In [https://pypi.org/project/prsaw/](https://pypi.org/project/prsaw/) it says using `rs.close()` is recommended. This is the code im using
```
    @commands.command(aliases=["c", "talk"])
    @cooldown(1, 3, BucketType.user)
    async def chat(self, ctx, *, args : str = None):
        if args is None:
            return await ctx.send("To use the chatbot function, you need to specify a second argument. Try Again")
        rs = RandomStuff()
        response = rs.get_ai_response(args, lang='en')

        await ctx.send(response)
        try:
            rs.close()
        except Exception as e:
            return await ctx.send(e)
```
when i execute this command, it sends the response obviously because it is above but afterward throws the error in the title

**Comment by CodeWithSwastik** [comment]
You are supposed to use 
```python
await rs.close()```
