### ISSUE TITLE
Custom Endpoints

### ISSUE THREAD

**Issue by ghost** [CodeWithSwastik/prsaw#5]
# PGamerX
I saw the code, you're using PGamerX's endpoints. He recently added ratelimits, as this is getting quite popular the chances that this would impact the module is huge. 

# Custom Endpoints
You could try and make your API which returns JSON using AI or however PGamerX did it. 
For instance: https://codewithswastik.github.io/endpoints/api?message="e"

Doing this makes the module last without any worries. 
**Eventually you know you would have to do this, or go to some API where you can abuse ratelimits lmao.**

I'm trying to make endpoints and I'm somewhere there.

**Comment by CodeWithSwastik** [comment]
The module is a wrapper for the random stuff api, we'll not be self hosting the api, it isn't open source.
