### ISSUE TITLE
Kinda worried about this

### ISSUE THREAD

**Issue by Cyanomous** [CodeWithSwastik/prsaw#7]
![image](https://user-images.githubusercontent.com/69328940/113619094-8ccb7600-9626-11eb-8ac3-09b99eaa824b.png)
If you send something random it sends something random back meaning it is possible for it to swear or say bad words etc.

**Comment by Cyanomous** [comment]
![image](https://user-images.githubusercontent.com/69328940/113619321-d3b96b80-9626-11eb-8c41-dce284091dc9.png)
and it still will say the same thing every once in a while

**Comment by FalseDev** [comment]
> ![image](https://user-images.githubusercontent.com/69328940/113619094-8ccb7600-9626-11eb-8ac3-09b99eaa824b.png)
> If you send something random it sends something random back meaning it is possible for it to swear or say bad words etc.

While you're not wrong, you should be contacting @pgamerxdev about this since this is only a wrapper

**Comment by CodeWithSwastik** [comment]
> > ![image](https://user-images.githubusercontent.com/69328940/113619094-8ccb7600-9626-11eb-8ac3-09b99eaa824b.png)
> > If you send something random it sends something random back meaning it is possible for it to swear or say bad words etc.
> 
> While you're not wrong, you should be contacting @pgamerxdev about this since this is only a wrapper

I agree with this, you should contact PGamerX about this, I'll be closing this issue.

**Comment by pgamerx** [comment]
> > ![image](https://user-images.githubusercontent.com/69328940/113619094-8ccb7600-9626-11eb-8ac3-09b99eaa824b.png)
> > If you send something random it sends something random back meaning it is possible for it to swear or say bad words etc.
> 
> While you're not wrong, you should be contacting @pgamerxdev about this since this is only a wrapper

Don't worry, It has possibly all the cuss words in the blacklist :)
